In [23]:
scraped_gender_stat = [{"label":"2010","value":25,"display":"25 Percent"},{"label":"2011","value":25.8175,"display":"25.8 Percent"},{"label":"2012","value":26.661732249999996,"display":"26.7 Percent"},{"label":"2013","value":27.533570894574993,"display":"27.5 Percent"},{"label":"2014","value":28.433918662827594,"display":"28.4 Percent"},{"label":"2015","value":29.363707803102056,"display":"29.4 Percent"},{"label":"2016","value":30.32390104826349,"display":"30.3 Percent"},{"label":"2017","value":31.315492612541707,"display":"31.3 Percent"},{"label":"2018","value":32.33950922097182,"display":"32.3 Percent"},{"label":"2019","value":33.3970111724976,"display":"33.4 Percent"},{"label":"2020","value":34.48909343783827,"display":"34.5 Percent"},{"label":"2021","value":35.616886793255574,"display":"35.6 Percent"},{"label":"2022","value":36.78155899139504,"display":"36.8 Percent"},{"label":"2023","value":37.984315970413654,"display":"38 Percent"}]

scraped_gender_stat = {
    int(item["label"]): item["value"]
    for item in scraped_gender_stat
}
print('The amount of female surfers through the years in % worldwide:\nSource: Priyanka Sharma. "Surfing Industry Statistics." Gitnux, 13 Feb 2026, https://gitnux.org/surfing-industry-statistics.')
display(scraped_gender_stat)

The amount of female surfers through the years in % worldwide:
Source: Priyanka Sharma. "Surfing Industry Statistics." Gitnux, 13 Feb 2026, https://gitnux.org/surfing-industry-statistics.

{2010: 25,
 2011: 25.8175,
 2012: 26.661732249999996,
 2013: 27.533570894574993,
 2014: 28.433918662827594,
 2015: 29.363707803102056,
 2016: 30.32390104826349,
 2017: 31.315492612541707,
 2018: 32.33950922097182,
 2019: 33.3970111724976,
 2020: 34.48909343783827,
 2021: 35.616886793255574,
 2022: 36.78155899139504,
 2023: 37.984315970413654}

In [14]:
import pandas as pd

injuries_stat_per_activity_1 = pd.DataFrame(
    [
        ["Walking (Recreational)", 214006, 4.7, 348589, 5.6, 3334, 6.7, 565929, 5.2],
        ["Running/jogging", 222460, 11.6, 168030, 12.0, 584, 3.3, 391074, 11.8],
        ["Football/soccer", 159918, 19.1, 37655, 16.9, 391, 10.7, 197964, 18.6],
        ["Bush walking", 64922, 3.8, 82503, 4.2, 1278, 6.6, 148703, 4.0],
        ["Basketball", 84635, 13.2, 22113, 9.9, 472, 11.9, 107220, 12.4],
        ["Australian football", 83425, 20.7, 16827, 15.8, 599, 42.5, 100851, 19.7],
        ["Cycling", 73546, 6.5, 21131, 3.0, 887, 10.3, 95564, 5.2],
        ["Tennis", 59380, 10.0, 27477, 6.6, 560, 24.0, 87417, 8.7],
        ["Netball", 9662, 15.4, 76235, 23.8, 455, 34.3, 86352, 22.5],
        ["Golf", 68249, 8.5, 14695, 7.7, None, None, 82945, 8.3],
        ["Swimming", 31868, 2.1, 33989, 2.0, 785, 4.4, 66642, 2.1],
        ["Cricket", 53835, 13.3, 5842, 8.8, None, None, 59678, 12.7],
        ["Pilates", 2422, 2.0, 40527, 3.3, 144, 3.7, 43093, 3.2],
        ["Hockey", 17386, 36.3, 15863, 33.7, None, None, 33250, 34.9],
        ["Athletics, track and field", 21973, 13.1, 9201, 10.6, None, None, 31174, 12.2],
        ["Volleyball", 18723, 16.4, 11360, 14.0, 198, 15.3, 30281, 15.4],
        ["Yoga", 8453, 5.1, 20323, 2.2, None, None, 28776, 2.7],
        ["Crossfit/Functional fitness", 10994, 20.3, 14432, 17.4, 210, 100.0, 25636, 18.7],
        ["Weight lifting", 17060, 11.2, 8246, 7.5, 194, 8.4, 25501, 9.6],
        ["Rugby league", 20140, 18.5, 4446, 13.7, 222, 21.4, 24809, 17.4],
    ],
    columns=[
        "activity",
        "male_estimate", "male_percent",
        "female_estimate", "female_percent",
        "other_estimate", "other_percent",
        "total_estimate", "total_percent",
    ],
)

display(injuries_stat_per_activity_1)

,activity,male_estimate,male_percent,female_estimate,female_percent,other_estimate,other_percent,total_estimate,total_percent
0,Walking (Recreational),214006,4.7,348589,5.6,3334.0,6.7,565929,5.2
1,Running/jogging,222460,11.6,168030,12.0,584.0,3.3,391074,11.8
2,Football/soccer,159918,19.1,37655,16.9,391.0,10.7,197964,18.6
3,Bush walking,64922,3.8,82503,4.2,1278.0,6.6,148703,4.0
4,Basketball,84635,13.2,22113,9.9,472.0,11.9,107220,12.4
5,Australian football,83425,20.7,16827,15.8,599.0,42.5,100851,19.7
6,Cycling,73546,6.5,21131,3.0,887.0,10.3,95564,5.2
7,Tennis,59380,10.0,27477,6.6,560.0,24.0,87417,8.7
8,Netball,9662,15.4,76235,23.8,455.0,34.3,86352,22.5
9,Golf,68249,8.5,14695,7.7,NaN,NaN,82945,8.3
10,Swimming,31868,2.1,33989,2.0,785.0,4.4,66642,2.1
11,Cricket,53835,13.3,5842,8.8,NaN,NaN,59678,12.7
12,Pilates,2422,2.0,40527,3.3,144.0,3.7,43093,3.2
13,Hockey,17386,36.3,15863,33.7,NaN,NaN,33250,34.9
14,"Athletics, track and field",21973,13.1,9201,10.6,NaN,NaN,31174,12.2
15,Volleyball,18723,16.4,11360,14.0,198.0,15.3,30281,15.4
16,Yoga,8453,5.1,20323,2.2,NaN,NaN,28776,2.7
17,Crossfit/Functional fitness,10994,20.3,14432,17.4,210.0,100.0,25636,18.7
18,Weight lifting,17060,11.2,8246,7.5,194.0,8.4,25501,9.6
19,Rugby league,20140,18.5,4446,13.7,222.0,21.4,24809,17.4

In [15]:
import pandas as pd

injuries_stat_per_activity_2 = pd.DataFrame(
    [
        ["Yoga", 8453, 5.1, 20323, 2.2, None, None, 28776, 2.7],
        ["Wrestling", 1243, 18.2, 166, 16.5, 185, 46.5, 1594, 19.3],
        ["Wood chopping", 274, 3.8, 234, 13.3, None, None, 508, 5.7],
        ["Weight lifting", 17060, 11.2, 8246, 7.5, 194, 8.4, 25501, 9.6],
        ["Waterskiing/Wakeboarding", 1291, 5.8, 622, 3.7, None, None, 1913, 4.9],
        ["Water polo", 1086, 11.0, 1091, 16.9, None, None, 2176, 13.3],
        ["Walking (Recreational)", 214006, 4.7, 348589, 5.6, 3334, 6.7, 565929, 5.2],
        ["Volleyball", 18723, 16.4, 11360, 14.0, 198, 15.3, 30281, 15.4],
        ["Virtual based physical activity", 2023, 2.1, 2498, 2.8, 205, 8.0, 4726, 2.6],
        ["Underwater sports", 1630, 1.8, 709, 0.8, None, None, 2339, 1.3],
        ["Triathlon", 2614, 14.8, 414, 4.3, None, None, 3028, 11.1],
        ["Touch football", 16121, 16.9, 7515, 15.2, None, None, 23636, 16.3],
        ["Tenpin bowling", 2000, 2.9, 1333, 2.2, None, None, 3333, 2.6],
        ["Tennis", 59380, 10.0, 27477, 6.6, 560, 24.0, 87417, 8.7],
        ["Taekwondo", 3726, 29.9, 1575, 18.2, None, None, 5302, 24.4],
        ["Table tennis", 4225, 1.9, 1520, 1.5, None, None, 5745, 1.8],
        ["Synchronised swimming", 362, 5.4, 385, 5.1, None, None, 748, 5.3],
        ["Sword fighting", 401, 18.9, None, None, None, None, 401, 10.1],
        ["Swimming", 31868, 2.1, 33989, 2.0, 785, 4.4, 66642, 2.1],
        ["Surfing", 16760, 9.5, 6047, 5.5, None, None, 22807, 7.9],
    ],
    columns=[
        "activity",
        "male_estimate", "male_percent",
        "female_estimate", "female_percent",
        "other_estimate", "other_percent",
        "total_estimate", "total_percent",
    ],
)

display(injuries_stat_per_activity_2)

,activity,male_estimate,male_percent,female_estimate,female_percent,other_estimate,other_percent,total_estimate,total_percent
0,Yoga,8453,5.1,20323.0,2.2,NaN,NaN,28776,2.7
1,Wrestling,1243,18.2,166.0,16.5,185.0,46.5,1594,19.3
2,Wood chopping,274,3.8,234.0,13.3,NaN,NaN,508,5.7
3,Weight lifting,17060,11.2,8246.0,7.5,194.0,8.4,25501,9.6
4,Waterskiing/Wakeboarding,1291,5.8,622.0,3.7,NaN,NaN,1913,4.9
5,Water polo,1086,11.0,1091.0,16.9,NaN,NaN,2176,13.3
6,Walking (Recreational),214006,4.7,348589.0,5.6,3334.0,6.7,565929,5.2
7,Volleyball,18723,16.4,11360.0,14.0,198.0,15.3,30281,15.4
8,Virtual based physical activity,2023,2.1,2498.0,2.8,205.0,8.0,4726,2.6
9,Underwater sports,1630,1.8,709.0,0.8,NaN,NaN,2339,1.3
10,Triathlon,2614,14.8,414.0,4.3,NaN,NaN,3028,11.1
11,Touch football,16121,16.9,7515.0,15.2,NaN,NaN,23636,16.3
12,Tenpin bowling,2000,2.9,1333.0,2.2,NaN,NaN,3333,2.6
13,Tennis,59380,10.0,27477.0,6.6,560.0,24.0,87417,8.7
14,Taekwondo,3726,29.9,1575.0,18.2,NaN,NaN,5302,24.4
15,Table tennis,4225,1.9,1520.0,1.5,NaN,NaN,5745,1.8
16,Synchronised swimming,362,5.4,385.0,5.1,NaN,NaN,748,5.3
17,Sword fighting,401,18.9,NaN,NaN,NaN,NaN,401,10.1
18,Swimming,31868,2.1,33989.0,2.0,785.0,4.4,66642,2.1
19,Surfing,16760,9.5,6047.0,5.5,NaN,NaN,22807,7.9

In [ ]:
injuries_stat_per_activity = (
    pd.concat(
        [injuries_stat_per_activity_1, injuries_stat_per_activity_2],
        ignore_index=True,
    )
    .drop_duplicates(subset="activity", keep="first")
    .reset_index(drop=True)
)
print("Injuries statistics per activity.\n Source: AUSPLAY. ")
display(injuries_stat_per_activity)

,activity,male_estimate,male_percent,female_estimate,female_percent,other_estimate,other_percent,total_estimate,total_percent
0,Walking (Recreational),214006,4.7,348589.0,5.6,3334.0,6.7,565929,5.2
1,Running/jogging,222460,11.6,168030.0,12.0,584.0,3.3,391074,11.8
2,Football/soccer,159918,19.1,37655.0,16.9,391.0,10.7,197964,18.6
3,Bush walking,64922,3.8,82503.0,4.2,1278.0,6.6,148703,4.0
4,Basketball,84635,13.2,22113.0,9.9,472.0,11.9,107220,12.4
5,Australian football,83425,20.7,16827.0,15.8,599.0,42.5,100851,19.7
6,Cycling,73546,6.5,21131.0,3.0,887.0,10.3,95564,5.2
7,Tennis,59380,10.0,27477.0,6.6,560.0,24.0,87417,8.7
8,Netball,9662,15.4,76235.0,23.8,455.0,34.3,86352,22.5
9,Golf,68249,8.5,14695.0,7.7,NaN,NaN,82945,8.3
10,Swimming,31868,2.1,33989.0,2.0,785.0,4.4,66642,2.1
11,Cricket,53835,13.3,5842.0,8.8,NaN,NaN,59678,12.7
12,Pilates,2422,2.0,40527.0,3.3,144.0,3.7,43093,3.2
13,Hockey,17386,36.3,15863.0,33.7,NaN,NaN,33250,34.9
14,"Athletics, track and field",21973,13.1,9201.0,10.6,NaN,NaN,31174,12.2
15,Volleyball,18723,16.4,11360.0,14.0,198.0,15.3,30281,15.4
16,Yoga,8453,5.1,20323.0,2.2,NaN,NaN,28776,2.7
17,Crossfit/Functional fitness,10994,20.3,14432.0,17.4,210.0,100.0,25636,18.7
18,Weight lifting,17060,11.2,8246.0,7.5,194.0,8.4,25501,9.6
19,Rugby league,20140,18.5,4446.0,13.7,222.0,21.4,24809,17.4
20,Wrestling,1243,18.2,166.0,16.5,185.0,46.5,1594,19.3
21,Wood chopping,274,3.8,234.0,13.3,NaN,NaN,508,5.7
22,Waterskiing/Wakeboarding,1291,5.8,622.0,3.7,NaN,NaN,1913,4.9
23,Water polo,1086,11.0,1091.0,16.9,NaN,NaN,2176,13.3
24,Virtual based physical activity,2023,2.1,2498.0,2.8,205.0,8.0,4726,2.6
25,Underwater sports,1630,1.8,709.0,0.8,NaN,NaN,2339,1.3
26,Triathlon,2614,14.8,414.0,4.3,NaN,NaN,3028,11.1
27,Touch football,16121,16.9,7515.0,15.2,NaN,NaN,23636,16.3
28,Tenpin bowling,2000,2.9,1333.0,2.2,NaN,NaN,3333,2.6
29,Taekwondo,3726,29.9,1575.0,18.2,NaN,NaN,5302,24.4
30,Table tennis,4225,1.9,1520.0,1.5,NaN,NaN,5745,1.8
31,Synchronised swimming,362,5.4,385.0,5.1,NaN,NaN,748,5.3
32,Sword fighting,401,18.9,NaN,NaN,NaN,NaN,401,10.1
33,Surfing,16760,9.5,6047.0,5.5,NaN,NaN,22807,7.9

In [20]:
import pandas as pd

male_sport_participation_with_age = pd.DataFrame(
    [
        [
            "Surfing",
            8339, 1.7,
            17066, 1.4,
            37414, 1.9,
            36548, 1.9,
            42061, 2.6,
            28529, None,
        ],
        [
            "Swimming",
            66680, 13.3,
            156745, 12.7,
            292264, 14.7,
            321909, 17.2,
            267191, 16.3,
            240736, None,
        ],
    ],
    columns=[
        "sport",
        "age_15_17_estimate", "age_15_17_participation_rate",
        "age_18_24_estimate", "age_18_24_participation_rate",
        "age_25_34_estimate", "age_25_34_participation_rate",
        "age_35_44_estimate", "age_35_44_participation_rate",
        "age_45_54_estimate", "age_45_54_participation_rate",
        "age_55_64_estimate", "age_55_64_participation_rate",
    ],
)
print("Here we can see male sport participation with age breakdown for Surfing and Swimming.\nSource: AUSPLAY. ")
display(male_sport_participation_with_age)

Here we can see male sport participation with age breakdown for Surfing and Swimming.
Source: AUSPLAY.

,sport,age_15_17_estimate,age_15_17_participation_rate,age_18_24_estimate,age_18_24_participation_rate,age_25_34_estimate,age_25_34_participation_rate,age_35_44_estimate,age_35_44_participation_rate,age_45_54_estimate,age_45_54_participation_rate,age_55_64_estimate,age_55_64_participation_rate
0,Surfing,8339,1.7,17066,1.4,37414,1.9,36548,1.9,42061,2.6,28529,None
1,Swimming,66680,13.3,156745,12.7,292264,14.7,321909,17.2,267191,16.3,240736,None

In [21]:
import pandas as pd

female_sport_participation_with_age = pd.DataFrame(
    [
        [
            "Surfing",
            9780, 2.1,
            14419, 1.3,
            29829, 1.5,
            27511, 1.4,
            17983, 1.1,
            15178, None,
        ],
        [
            "Swimming",
            103859, 22.0,
            207692, 18.1,
            367771, 18.6,
            359130, 18.8,
            282145, 16.8,
            236436, None,
        ],
    ],
    columns=[
        "sport",
        "age_15_17_estimate", "age_15_17_participation_rate",
        "age_18_24_estimate", "age_18_24_participation_rate",
        "age_25_34_estimate", "age_25_34_participation_rate",
        "age_35_44_estimate", "age_35_44_participation_rate",
        "age_45_54_estimate", "age_45_54_participation_rate",
        "age_55_64_estimate", "age_55_64_participation_rate",
    ],
)

print("Female sport participation by age, for Surfing and Swimming.\nSource: AUSPLAY. ")
display(female_sport_participation_with_age)

Female sport participation by age, for Surfing and Swimming.
Source: AUSPLAY.

,sport,age_15_17_estimate,age_15_17_participation_rate,age_18_24_estimate,age_18_24_participation_rate,age_25_34_estimate,age_25_34_participation_rate,age_35_44_estimate,age_35_44_participation_rate,age_45_54_estimate,age_45_54_participation_rate,age_55_64_estimate,age_55_64_participation_rate
0,Surfing,9780,2.1,14419,1.3,29829,1.5,27511,1.4,17983,1.1,15178,None
1,Swimming,103859,22.0,207692,18.1,367771,18.6,359130,18.8,282145,16.8,236436,None