In [1]:
import pandas as pd
import numpy as np

In [2]:
shark_attacks = pd.read_csv("GSAF5.csv")
display(shark_attacks)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th September,2026.0,Unprovoked,Australia,Western Australia,Sorrento Beach Perth,Swimming,Greg O'Neil,M,63,...,Great White Shark 6m (20ft),Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16th September,2026.0,Unprovoked,Canada,Quebec,Off the coast of Perce Le Bilbo dive site,Diving,Unknown Male,M,?,...,Great White Shark,Keith Cowley: Kevin McMurray Trackingsharks.co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14th September,2026.0,Unprovoked,Bahamas,Bimini,Bimini Island,Swimming,Unknown Austrian Tourist,F,37,...,Unknown,Kevin McMurray Trackingsharks.com: Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13th September,2026.0,Unprovoked,Australia,Western Australia,Geraldton,Surfing,Mel Ismail,M,50's,...,Unknown,Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7th September,2026.0,Unprovoked,USA,Hawaii,Honolulu,Surfing,Wants to remain anonymous,M,24,...,Tiger Shark suspected,Keith Cowley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7120,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7121,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7122,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7123,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7124,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [3]:
print("\nColumns:")
display(shark_attacks.columns.tolist())
print("\nInfo:")
display(shark_attacks.info())
print("\nData types:")
display(shark_attacks.dtypes)

Columns:

['Date',
 'Year',
 'Type',
 'Country',
 'State',
 'Location',
 'Activity',
 'Name',
 'Sex',
 'Age',
 'Injury',
 'Fatal Y/N',
 'Time',
 'Species ',
 'Source',
 'pdf',
 'href formula',
 'href',
 'Case Number',
 'Case Number.1',
 'original order',
 'Unnamed: 21',
 'Unnamed: 22']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 7125 entries, 0 to 7124
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7125 non-null   str
 1   Year            7123 non-null   float64
 2   Type            7107 non-null   str
 3   Country         7075 non-null   str
 4   State           6638 non-null   str
 5   Location        6558 non-null   str
 6   Activity        6542 non-null   str
 7   Name            6907 non-null   str
 8   Sex             6547 non-null   str
 9   Age             4131 non-null   str
 10  Injury          7089 non-null   str
 11  Fatal Y/N       6564 non-null   str
 12  Time            3598 non-null   str
 13  Species         3994 non-null   str
 14  Source          7105 non-null   str
 15  pdf             6799 non-null   str
 16  href formula    6794 non-null   str
 17  href            6796 non-null   str
 18  Case Number     6798 non-null   str
 19  Case Number.1   6797 non-null   str
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      str
 22  Unnamed: 22     2 non-null      str
dtypes: float64(2), str(21)
memory usage: 1.3 MB

None

Data types:

Date                  str
Year              float64
Type                  str
Country               str
State                 str
Location              str
Activity              str
Name                  str
Sex                   str
Age                   str
Injury                str
Fatal Y/N             str
Time                  str
Species               str
Source                str
pdf                   str
href formula          str
href                  str
Case Number           str
Case Number.1         str
original order    float64
Unnamed: 21           str
Unnamed: 22           str
dtype: object

In [4]:
attacks_reduced = shark_attacks.drop(columns=["State","Name",'Time',"Source",'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'])

display(attacks_reduced)

,Date,Year,Type,Country,Location,Activity,Sex,Age,Injury,Fatal Y/N,Species
0,18th September,2026.0,Unprovoked,Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,Unknown
3,13th September,2026.0,Unprovoked,Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,Unknown
4,7th September,2026.0,Unprovoked,USA,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...
7120,Before 1903,0.0,Unprovoked,AUSTRALIA,Roebuck Bay,Diving,M,NaN,FATAL,Y,NaN
7121,Before 1903,0.0,Unprovoked,AUSTRALIA,NaN,Pearl diving,M,NaN,FATAL,Y,NaN
7122,1900-1905,0.0,Unprovoked,USA,Ocracoke Inlet,Swimming,M,NaN,FATAL,Y,NaN
7123,1883-1889,0.0,Unprovoked,PANAMA,"Panama Bay 8ºN, 79ºW",NaN,M,NaN,FATAL,Y,NaN
7124,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),"Below the English fort, Trincomalee",Swimming,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN

In [6]:
print("\nMissing values:")
display(attacks_reduced.isna().sum())

Missing values:

Date            0
Year            2
Type           18
Country        50
Location      567
Activity      583
Sex           578
Age          2994
Injury         36
Fatal Y/N     561
Species      3131
dtype: int64

In [7]:
without_missing_sex = attacks_reduced.dropna(subset=["Sex"])
display(without_missing_sex)

,Date,Year,Type,Country,Location,Activity,Sex,Age,Injury,Fatal Y/N,Species
0,18th September,2026.0,Unprovoked,Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,Unknown
3,13th September,2026.0,Unprovoked,Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,Unknown
4,7th September,2026.0,Unprovoked,USA,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...
7120,Before 1903,0.0,Unprovoked,AUSTRALIA,Roebuck Bay,Diving,M,NaN,FATAL,Y,NaN
7121,Before 1903,0.0,Unprovoked,AUSTRALIA,NaN,Pearl diving,M,NaN,FATAL,Y,NaN
7122,1900-1905,0.0,Unprovoked,USA,Ocracoke Inlet,Swimming,M,NaN,FATAL,Y,NaN
7123,1883-1889,0.0,Unprovoked,PANAMA,"Panama Bay 8ºN, 79ºW",NaN,M,NaN,FATAL,Y,NaN
7124,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),"Below the English fort, Trincomalee",Swimming,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN

In [8]:
print("\nMissing values:")
display(without_missing_sex.isna().sum())

Missing values:

Date            0
Year            2
Type           18
Country        46
Location      500
Activity      430
Sex             0
Age          2456
Injury         21
Fatal Y/N     480
Species      2879
dtype: int64

In [9]:
without_missing_sex.columns = (
    without_missing_sex.columns #takes the column names of the DataFrame
    .str.strip() #removes leading and trailing whitespace from the column names
    .str.lower() #converts the column names to lowercase
    .str.replace(" ", "_") #replaces spaces with underscores in the column names
)

print(without_missing_sex.columns.tolist())

['date', 'year', 'type', 'country', 'location', 'activity', 'sex', 'age', 'injury', 'fatal_y/n', 'species']

In [10]:
for column in without_missing_sex.describe(include=["O"]).columns:
    print(without_missing_sex[column].value_counts())
    print()

date
1957                                                                8
1956                                                                7
1950                                                                7
1942                                                                7
1941                                                                7
                                                                   ..
No date (3 days after preceding incident) & prior to 19-Jul-1913    1
Before 19-Jul-1913                                                  1
1900-1905                                                           1
1883-1889                                                           1
1845-1853                                                           1
Name: count, Length: 5658, dtype: int64

type
Unprovoked             5102
Provoked                588
Invalid                 478
Sea Disaster            177
Watercraft              151
Questionable             26
 Provoked                 2
UNprovoked                1
unprovoked                1
?                         1
Unverified                1
Under investigation       1
Name: count, dtype: int64

country
USA                   2493
AUSTRALIA             1337
SOUTH AFRICA           532
BAHAMAS                133
NEW ZEALAND            129
                      ...
BAHREIN                  1
KOREA                    1
RED SEA?                 1
ASIA?                    1
CEYLON (SRI LANKA)       1
Name: count, Length: 249, dtype: int64

location
New Smyrna Beach, Volusia County       188
Daytona Beach, Volusia County           30
Ponce Inlet, Volusia County             27
Myrtle Beach, Horry County              22
Melbourne Beach, Brevard County         20
                                      ...
                                         1
Roebuck Bay                              1
Ocracoke Inlet                           1
Panama Bay 8ºN, 79ºW                     1
Below the English fort, Trincomalee      1
Name: count, Length: 4306, dtype: int64

activity
Surfing                                               1131
Swimming                                              1005
Fishing                                                401
Spearfishing                                           382
Wading                                                 175
                                                      ...
Wooden fishing boat                                      1
Swimming in pool formed by construction of a wharf       1
Swimming around anchored ship                            1
Crew swimming alongside their anchored ship              1
4 men were bathing                                       1
Name: count, Length: 1461, dtype: int64

sex
M        5709
F         818
M           8
?           2
F           2
N           2
M F         1
 M          1
m           1
lli         1
M x 2       1
.           1
Name: count, dtype: int64

age
17             174
18             158
20             155
15             155
19             151
              ...
?    &   14      1
10 or 12         1
31 or 33         1
2½               1
13 or 14         1
Name: count, Length: 171, dtype: int64

injury
FATAL                                                                                                     819
Foot bitten                                                                                                98
Leg bitten                                                                                                 79
Survived                                                                                                   79
No injury                                                                                                  78
                                                                                                         ...
"Lost leg"                                                                                                  1
FATAL, body not recovered but shark was caught with the man's loincloth in its gut shortly afterwards.      1
FATAL, leg stripped of flesh                                                                                1
FATAL, knocked overboard by tail of shark & carried off by shark                                            1
FATAL. "Shark bit him in half, carrying away the lower extremities"                                         1
Name: count, Length: 3852, dtype: int64

fatal_y/n
N          4618
Y          1389
UNKNOWN      40
 N            7
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
y             1
Name: count, dtype: int64

species
White shark                                                                                                                      168
Invalid                                                                                                                           88
Shark involvement prior to death was not confirmed                                                                                86
Tiger shark                                                                                                                       85
Shark involvement not confirmed                                                                                                   82
                                                                                                                                ...
Bull shark caught, leg recovered & buried beside the man's body                                                                    1
"a black-tipped shark"                                                                                                             1
12' tiger shark                                                                                                                    1
Blue pointers                                                                                                                      1
Said to involve a grey nurse shark that leapt out of the water and  seized the boy but species identification is questionable      1
Name: count, Length: 1654, dtype: int64

/var/folders/nh/3s3pvk8j0gxgybrdb2nsc99h0000gp/T/ipykernel_66251/1999832831.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in without_missing_sex.describe(include=["O"]).columns:

In [11]:
#filtering dataframe, only data since year 2000
without_missing_sex["year"] = pd.to_numeric(without_missing_sex["year"], errors="coerce")

attacks_reduced_2000_onward = without_missing_sex[without_missing_sex["year"] >= 2000].copy()
display(attacks_reduced_2000_onward)

,date,year,type,country,location,activity,sex,age,injury,fatal_y/n,species
0,18th September,2026.0,Unprovoked,Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,Great White Shark 6m (20ft)
1,16th September,2026.0,Unprovoked,Canada,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,Great White Shark
2,14th September,2026.0,Unprovoked,Bahamas,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,Unknown
3,13th September,2026.0,Unprovoked,Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,Unknown
4,7th September,2026.0,Unprovoked,USA,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,Tiger Shark suspected
...,...,...,...,...,...,...,...,...,...,...,...
2868,03-Feb-2000,2000.0,Unprovoked,NEW ZEALAND,Oreti Beach (reported as the 4th person bitten...,Surfing,M,12,"No injury, wetsuit punctured",N,NaN
2869,01-Feb-2000,2000.0,Unprovoked,AUSTRALIA,"Point Sinclair, Cactus Beach near Penong",Surfing,M,26,Hand bitten,N,3 m [10'] shark
2870,Reported 28-Jan-2000,2000.0,Watercraft,REUNION,Saint Pierre,Canoe with 3 men onboard sank,M,NaN,FATAL,Y,NaN
2871,05-Jan-2000,2000.0,Unprovoked,THAILAND,Phang nga Island,Diving,M,35,FATAL,Y,NaN
2872,2000,2000.0,Watercraft,USA,"Boca Grande, Lee County",Fishing for tarpon,M,NaN,No injury to occupant; shark bit propeller,N,Hammerhead shark

In [12]:
print("\nMissing values:")
display(attacks_reduced_2000_onward.isna().sum())

Missing values:

date           0
year           0
type          14
country        2
location     100
activity     103
sex            0
age          562
injury         7
fatal_y/n    162
species      957
dtype: int64

In [13]:
print("\nDuplicated rows:")
print(attacks_reduced_2000_onward.duplicated().sum())

Duplicated rows:
0

In [14]:
print("\nDate:")
display(attacks_reduced_2000_onward["date"].value_counts())

Date:

date
07/04/2024              5
05-Oct-2003             5
12-Apr-2001             5
04 Jul-2023             4
15-Apr-2018             4
                       ..
03-Feb-2000             1
01-Feb-2000             1
Reported 28-Jan-2000    1
05-Jan-2000             1
2000                    1
Name: count, Length: 2311, dtype: int64

In [15]:
import re

In [18]:
#pd.to_datetime(attacks_reduced_2000_onward.date)

In [ ]:

# Normalize full month names and common abbreviations to full month names.
month_aliases = {
   "jan": "January", "january": "January",
    "feb": "February", "february": "February",
    "mar": "March", "march": "March",
    "apr": "April", "april": "April",
    "may": "May",
    "jun": "June", "june": "June",
    "jul": "July", "july": "July",
    "aug": "August", "august": "August",
    "sep": "September", "sept": "September", "september": "September",
    "oct": "October", "october": "October",
    "nov": "November", "november": "November",
    "dec": "December", "december": "December",
}
months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]
month_pattern = r"\\b(" + "|".join(month_aliases) + r")\\b"
extracted_months = (
    attacks_reduced_2000_onward["date"]
    .astype("string")
    .str.lower()
    .str.extract(month_pattern, expand=False)
)
attacks_reduced_2000_onward["month"] = pd.Categorical(
    extracted_months.map(month_aliases),
    categories=months,
    ordered=True,
)

# Inspect any dates for which no month name or abbreviation was found.
print(attacks_reduced_2000_onward.loc[attacks_reduced_2000_onward["month"].isna(), "date"].head())
attacks_reduced_2000_onward = attacks_reduced_2000_onward.drop(columns=["date"])
display(attacks_reduced_2000_onward)

#display unique values months
display(attacks_reduced_2000_onward["month"].unique())

0    09/18/2026
1    09/16/2026
2    09/14/2026
3    09/13/2026
4    09/07/2026
Name: date, dtype: str

,year,type,country,location,activity,sex,age,injury,fatal_y/n,species,month
0,2026.0,Unprovoked,Australia,Sorrento Beach Perth,Swimming,M,63,Body not recovered,Y,Great White Shark 6m (20ft),NaN
1,2026.0,Unprovoked,Canada,Off the coast of Perce Le Bilbo dive site,Diving,M,?,Injuries to chest shoulder and back,N,Great White Shark,NaN
2,2026.0,Unprovoked,Bahamas,Bimini Island,Swimming,F,37,Serious injuries to right ankle,N,Unknown,NaN
3,2026.0,Unprovoked,Australia,Geraldton,Surfing,M,50's,Foot lost in attack,N,Unknown,NaN
4,2026.0,Unprovoked,USA,Honolulu,Surfing,M,24,Scrapes on inside of legs,N,Tiger Shark suspected,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2868,2000.0,Unprovoked,NEW ZEALAND,Oreti Beach (reported as the 4th person bitten...,Surfing,M,12,"No injury, wetsuit punctured",N,NaN,NaN
2869,2000.0,Unprovoked,AUSTRALIA,"Point Sinclair, Cactus Beach near Penong",Surfing,M,26,Hand bitten,N,3 m [10'] shark,NaN
2870,2000.0,Watercraft,REUNION,Saint Pierre,Canoe with 3 men onboard sank,M,NaN,FATAL,Y,NaN,NaN
2871,2000.0,Unprovoked,THAILAND,Phang nga Island,Diving,M,35,FATAL,Y,NaN,NaN
2872,2000.0,Watercraft,USA,"Boca Grande, Lee County",Fishing for tarpon,M,NaN,No injury to occupant; shark bit propeller,N,Hammerhead shark,NaN